# Generated by Django 2.0.9 on 2018-10-30 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='FechaNacimiento',
            field=models.DateField(null=True),
        ),
    ]
