# Generated by Django 2.0.9 on 2018-11-17 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0002_auto_20181029_2359'),
    ]

    operations = [
        migrations.CreateModel(
            name='PerrosRescatados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fotografia', models.ImageField(upload_to='')),
                ('NombrePerro', models.CharField(max_length=200)),
                ('RazaPredominante', models.CharField(max_length=200)),
                ('Descripcion', models.TextField()),
                ('Estado', models.CharField(choices=[('R', 'Rescatado'), ('D', 'Disponible'), ('A', 'Adoptado')], default='R', max_length=1)),
            ],
        ),
    ]
