# Generated by Django 2.0.9 on 2018-11-17 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0003_perrosrescatados'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perrosrescatados',
            name='Fotografia',
            field=models.ImageField(upload_to='imagenesPerros/'),
        ),
    ]
