# Generated by Django 2.0.9 on 2018-11-20 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Usuarios', '0007_auto_20181118_1934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfilusuario',
            name='Comuna',
        ),
        migrations.RemoveField(
            model_name='perfilusuario',
            name='Region',
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='ApellidoUser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='CorreoElectronico',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='NombreUser',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='Run',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
